### ISSUE TITLE
Incorrect Rating Predictions for Past Contests

### ISSUE THREAD

**Issue by wesley-a-leung** [Ninjaclasher/dmoj-rating-predictor#1]
There appears to be an issue when displaying rating changes for pasts contests. There are small errors in the predicted rating changes, and the actual rating changes for these contests.

One example of the following is when looking at [DMOPC '19 September](https://dmoj.ca/contest/dmopc19c1/ranking/). On the right hand side of each row we can see the rating changes as seen below:

![image](https://user-images.githubusercontent.com/9375453/78961883-db503e00-7ac0-11ea-8613-dcf3895e3ffa.png)

In this image, we can see that the user `wleung_bvg` is expected to lose 5 rating points. However, in this contest, the actual rating drop was 6 rating points. Similar behaviour is observed with other users. The error appears to increase as you move further down the scoreboard.

## Reproduction Steps

1. Download the extension from [GitHub](https://github.com/Ninjaclasher/dmoj-rating-predictor).
2. Unzip the extension into a folder
3. Go to the Chrome Extensions Menu (chrome://extensions/), select `Load unpacked`, and select the folder containing the unzipped repository.
4. Visit the [DMOPC '19 September scoreboard](https://dmoj.ca/contest/dmopc19c1/ranking/) and observe the rating prediction on the rightmost column.

## Expected Behaviour
The rating predictor displays the correct rating changes for both ongoing contests and past contests.

## Actual Behaviour
The rating predictor incorrectly displays the rating changes for some pasts contests, such as DMOPC '19 September.

## Build Information
Version 0.0.1 was used, downloaded from [GitHub](https://github.com/Ninjaclasher/dmoj-rating-predictor) on April 10, 2020 at 00:01 EDT.

**Comment by Ninjaclasher** [comment]
The DMOJ sometimes rerates their contests with different parameters long after the contest has ended. Unfortunately, the rating predictor does not retroactively recompute contest rating changes, and it would be too computationally intensive at this point in time. Thus, only current rating changes should be considered "accurate".

Once I rewrite the backend to support recomputing rating changes,  this will hopefully be fixed. Sorry about that.

**Comment by Ninjaclasher** [comment]
This *should* be fixed now. Let me know if this issue persists. There are no frontend changes, so there is no need to update the extension.
